import type { CSSProperties } from 'react';

const styles = {
  root: {
    padding: '8px 12px',
  },
  card: {
    position: 'relative',
    borderRadius: 12,
    background: 'linear-gradient(180deg, #ecd9a8 0%, #e2c98d 100%)',
    boxShadow: '0 3px 8px rgba(0,0,0,0.35)',
  },
  body: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '18px 12px 12px',
  },
  hero: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
    minWidth: 76,
  },
  heroIcon: {
    fontSize: 40,
    lineHeight: 1,
    filter: 'drop-shadow(0 2px 3px rgba(0,0,0,0.4))',
  },
  heroAmount: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 900,
    textShadow: '0 1.5px 0 #7a5215, 0 2px 3px rgba(0,0,0,0.45)',
    whiteSpace: 'nowrap',
  },
  heroOldAmount: {
    color: '#f6352b',
    fontSize: 12,
    fontWeight: 800,
    textDecoration: 'line-through',
    whiteSpace: 'nowrap',
  },
  itemsGrid: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '10px 6px',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  itemIcon: {
    fontSize: 24,
    lineHeight: 1,
    filter: 'drop-shadow(0 2px 2px rgba(0,0,0,0.35))',
  },
  itemAmount: {
    color: '#5b3d17',
    fontSize: 11,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  badge: {
    position: 'absolute',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: 44,
    height: 44,
    borderRadius: '50%',
    color: '#ffffff',
    fontSize: 9,
    fontWeight: 900,
    fontStyle: 'italic',
    lineHeight: 1.1,
    textShadow: '0 1px 2px rgba(0,0,0,0.4)',
    boxShadow: '0 2px 4px rgba(0,0,0,0.35), inset 0 0 0 2px rgba(255,255,255,0.35)',
  },
  badgeTopLeft: {
    top: -8,
    left: -8,
    transform: 'rotate(-10deg)',
    background: 'radial-gradient(circle at 35% 30%, #56c2ff, #1d7fd6)',
  },
  badgeTopRight: {
    top: -8,
    right: -8,
    transform: 'rotate(10deg)',
    background: 'radial-gradient(circle at 35% 30%, #d97bff, #9c2fd6)',
  },
  buyBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 0',
    borderRadius: '0 0 12px 12px',
    background: 'linear-gradient(180deg, #9fdd4f 0%, #63b52a 55%, #4c9c1d 100%)',
    boxShadow: 'inset 0 2px 0 rgba(255,255,255,0.4)',
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 900,
    textShadow: '0 1px 2px rgba(0,0,0,0.45)',
  },
} satisfies Record<string, CSSProperties>;

export default styles;
