import type { CSSProperties } from 'react';

const styles = {
  root: {
    padding: '8px 12px 12px',
  },
  timerBand: {
    textAlign: 'center',
    padding: '8px 0',
    borderRadius: '10px 10px 0 0',
    background: 'linear-gradient(180deg, #5a1f2b 0%, #471722 100%)',
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 800,
    textShadow: '0 1px 2px rgba(0,0,0,0.6)',
  },
  carousel: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    background: 'linear-gradient(180deg, #6e2433 0%, #591c28 100%)',
    borderRadius: '0 0 10px 10px',
    padding: '10px 34px',
  },
  arrow: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    width: 26,
    height: 26,
    borderRadius: '50%',
    background: 'rgba(0,0,0,0.65)',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    cursor: 'pointer',
    zIndex: 1,
  },
  card: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    background: 'linear-gradient(180deg, #efdcae 0%, #e3c98d 100%)',
    boxShadow: '0 2px 5px rgba(0,0,0,0.35)',
  },
  itemsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 8,
    padding: '12px 10px',
  },
  item: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3,
  },
  itemIcon: {
    fontSize: 24,
    lineHeight: 1,
    filter: 'drop-shadow(0 2px 2px rgba(0,0,0,0.35))',
  },
  itemAmount: {
    color: '#5b3d17',
    fontSize: 10.5,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  buyBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '9px 0',
    background: 'linear-gradient(180deg, #9fdd4f 0%, #63b52a 55%, #4c9c1d 100%)',
    boxShadow: 'inset 0 2px 0 rgba(255,255,255,0.4)',
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 900,
    textShadow: '0 1px 2px rgba(0,0,0,0.45)',
  },
  oldPrice: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 11,
    fontWeight: 700,
    textDecoration: 'line-through',
  },
  dots: {
    display: 'flex',
    justifyContent: 'center',
    gap: 5,
    paddingTop: 8,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    background: 'rgba(0,0,0,0.3)',
  },
  dotActive: {
    background: '#5b3d17',
  },
} satisfies Record<string, CSSProperties>;

export default styles;
